# Make sure this is set to "kotlinforforge"
modLoader="kotlinforforge"
# Make sure this is set to the appropriate version range
loaderVersion="[3,)" # Require at least 3.x
# License is REQUIRED after 1.16
license='LGPL'

[[mods]]
modId="examplemod"
version="${file.jarVersion}"
displayName="ExampleMod"
credits="The ExampleMod dev team"
authors="ExampleModAuthor"
description='''
Example mod that uses Kotlin for Forge.
'''
[[dependencies.examplemod]]
    modId="forge"
    mandatory=true
    versionRange="[41,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
